#!/usr/bin/env python3
import sys
import os
import helpers
from analyzer import Analyzer 
from termcolor import colored


def main():
    
    # ensure proper usage
    if len(sys.argv) != 2:
        sys.exit("Usage: ./tweets @screen_name")
        
    # obtain tweets
    tweets = helpers.get_user_timeline(sys.argv[1].strip("@"), count=50)
    if tweets == None:
        sys.exit("Unable to load tweets.")
    
    # initiate analyzer with absolute paths to word files
    positives = os.path.join(sys.path[0], "positive-words.txt")
    negatives = os.path.join(sys.path[0], "negative-words.txt")
    analyzer = Analyzer(positives, negatives)
    
    # analyze tweets
    for tweet in tweets:
        score = analyzer.analyze(tweet)
        if score > 0.0:
            print(colored(" " + str(score) + " " + tweet, "green"))
        elif score < 0.0:
            print(colored(" " + str(score) + " " + tweet, "red"))
        else:
            print(colored(" " + str(score) + " " + tweet, "yellow"))
    
# initiate main function
if __name__ == "__main__":
    main()